package org.sv.ues.igf.entidades;

// Generated 10-25-2014 10:33:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientetarjetaId generated by hbm2java
 */
@Embeddable
public class ClientetarjetaId implements java.io.Serializable {

	private int idtarjetacredito;
	private int idcliente;

	public ClientetarjetaId() {
	}

	public ClientetarjetaId(int idtarjetacredito, int idcliente) {
		this.idtarjetacredito = idtarjetacredito;
		this.idcliente = idcliente;
	}

	@Column(name = "idtarjetacredito", nullable = false)
	public int getIdtarjetacredito() {
		return this.idtarjetacredito;
	}

	public void setIdtarjetacredito(int idtarjetacredito) {
		this.idtarjetacredito = idtarjetacredito;
	}

	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientetarjetaId))
			return false;
		ClientetarjetaId castOther = (ClientetarjetaId) other;

		return (this.getIdtarjetacredito() == castOther.getIdtarjetacredito())
				&& (this.getIdcliente() == castOther.getIdcliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdtarjetacredito();
		result = 37 * result + this.getIdcliente();
		return result;
	}

}
