package org.sv.ues.igf.entidades;

// Generated 10-25-2014 10:33:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientetarjetaestadoId generated by hbm2java
 */
@Embeddable
public class ClientetarjetaestadoId implements java.io.Serializable {

	private int idtarjetacredito;
	private int idcliente;
	private Date fechaLimitePago;

	public ClientetarjetaestadoId() {
	}

	public ClientetarjetaestadoId(int idtarjetacredito, int idcliente,
			Date fechaLimitePago) {
		this.idtarjetacredito = idtarjetacredito;
		this.idcliente = idcliente;
		this.fechaLimitePago = fechaLimitePago;
	}

	@Column(name = "idtarjetacredito", nullable = false)
	public int getIdtarjetacredito() {
		return this.idtarjetacredito;
	}

	public void setIdtarjetacredito(int idtarjetacredito) {
		this.idtarjetacredito = idtarjetacredito;
	}

	@Column(name = "idcliente", nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "fecha_limite_pago", nullable = false, length = 10)
	public Date getFechaLimitePago() {
		return this.fechaLimitePago;
	}

	public void setFechaLimitePago(Date fechaLimitePago) {
		this.fechaLimitePago = fechaLimitePago;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClientetarjetaestadoId))
			return false;
		ClientetarjetaestadoId castOther = (ClientetarjetaestadoId) other;

		return (this.getIdtarjetacredito() == castOther.getIdtarjetacredito())
				&& (this.getIdcliente() == castOther.getIdcliente())
				&& ((this.getFechaLimitePago() == castOther
						.getFechaLimitePago()) || (this.getFechaLimitePago() != null
						&& castOther.getFechaLimitePago() != null && this
						.getFechaLimitePago().equals(
								castOther.getFechaLimitePago())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdtarjetacredito();
		result = 37 * result + this.getIdcliente();
		result = 37
				* result
				+ (getFechaLimitePago() == null ? 0 : this.getFechaLimitePago()
						.hashCode());
		return result;
	}

}
