package org.sv.ues.igf.entidades;

// Generated 10-25-2014 10:33:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "clave1")
public class Pais implements java.io.Serializable {

	private Short idpais;
	private String nombrePais;
	private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

	public Pais() {
	}

	public Pais(String nombrePais, Set<Transaccion> transaccions) {
		this.nombrePais = nombrePais;
		this.transaccions = transaccions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpais", unique = true, nullable = false)
	public Short getIdpais() {
		return this.idpais;
	}

	public void setIdpais(Short idpais) {
		this.idpais = idpais;
	}

	@Column(name = "nombre_pais", length = 45)
	public String getNombrePais() {
		return this.nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Transaccion> getTransaccions() {
		return this.transaccions;
	}

	public void setTransaccions(Set<Transaccion> transaccions) {
		this.transaccions = transaccions;
	}

}
