package org.sv.ues.igf.entidades;

// Generated 10-25-2014 10:33:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tipocliente generated by hbm2java
 */
@Entity
@Table(name = "tipocliente", catalog = "clave1")
public class Tipocliente implements java.io.Serializable {

	private String idtipocliente;
	private String DTipoCliente;
	private Date fechIngres;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Tipocliente() {
	}

	public Tipocliente(String idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	public Tipocliente(String idtipocliente, String DTipoCliente,
			Date fechIngres, Set<Cliente> clientes) {
		this.idtipocliente = idtipocliente;
		this.DTipoCliente = DTipoCliente;
		this.fechIngres = fechIngres;
		this.clientes = clientes;
	}

	@Id
	@Column(name = "idtipocliente", unique = true, nullable = false, length = 3)
	public String getIdtipocliente() {
		return this.idtipocliente;
	}

	public void setIdtipocliente(String idtipocliente) {
		this.idtipocliente = idtipocliente;
	}

	@Column(name = "d_tipo_cliente", length = 25)
	public String getDTipoCliente() {
		return this.DTipoCliente;
	}

	public void setDTipoCliente(String DTipoCliente) {
		this.DTipoCliente = DTipoCliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fech_ingres", length = 10)
	public Date getFechIngres() {
		return this.fechIngres;
	}

	public void setFechIngres(Date fechIngres) {
		this.fechIngres = fechIngres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocliente")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
